app/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask import Flask
from config import config


def create_app(config_name):
    """ 使用工厂函数初始化程序实例"""
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app=app)

    # 注册蓝本 lib
    from .lib import lib as lib_blueprint
    app.register_blueprint(lib_blueprint, url_prefix='/lib')

    # 注册蓝本 basic
    from .basic import basic as basic_blueprint
    app.register_blueprint(basic_blueprint, url_prefix='/basic')

    # 注册蓝本 advanced
    from .advanced import advanced as advanced_blueprint
    app.register_blueprint(advanced_blueprint, url_prefix='/advanced')

    # 注册蓝本 folder
    from .folder import folder as folder_blueprint
    app.register_blueprint(folder_blueprint, url_prefix='/folder')

    return app

app/advanced/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'


from flask import Blueprint


advanced = Blueprint('advanced', __name__, template_folder="templates", static_folder='static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本 basic
from . import views

app/advanced/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask import render_template, request, jsonify
from . import advanced


@advanced.route('/delete', methods=['GET', 'POST'])
def delete():
    key = request.form.get('key')
    print key

    return jsonify()


@advanced.route('/example_1', methods=['GET', 'POST'])
def example_1():

    return render_template('exam_1.html')


@advanced.route('/example_2', methods=['GET', 'POST'])
def example_2():

    return render_template('exam_2.html')


@advanced.route('/example_3', methods=['GET', 'POST'])
def example_3():

    return render_template('exam_3.html')


@advanced.route('/example_4', methods=['GET', 'POST'])
def example_4():

    return render_template('exam_4.html')


@advanced.route('/example_5', methods=['GET', 'POST'])
def example_5():

    return render_template('exam_5.html')


@advanced.route('/example_6', methods=['GET', 'POST'])
def example_6():

    return render_template('exam_6.html')


@advanced.route('/example_7', methods=['GET', 'POST'])
def example_7():

    return render_template('exam_7.html')


@advanced.route('/example_8', methods=['GET', 'POST'])
def example_8():

    return render_template('exam_8.html')


@advanced.route('/example_9', methods=['GET', 'POST'])
def example_9():

    return render_template('exam_9.html')


@advanced.route('/example_10', methods=['GET', 'POST'])
def example_10():

    return render_template('exam_10.html')


@advanced.route('/example_11', methods=['GET', 'POST'])
def example_11():

    return render_template('exam_11.html')

app/basic/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'


from flask import Blueprint


basic = Blueprint('basic', __name__, template_folder="templates", static_folder='static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本 basic
from . import views

app/basic/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask import render_template, request, current_app, redirect, url_for
from . import basic
from werkzeug.utils import secure_filename
import os


def allowed_file(filename):
    ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@basic.route('/example_1', methods=['GET', 'POST'])
def example_1():
    if request.method == 'POST':
        file = request.files['input-1']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

    return render_template('example_1.html')


@basic.route('/example_2', methods=['GET', 'POST'])
def example_2():
    if request.method == 'POST':
        file = request.files['input-2']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

    return render_template('example_2.html')


@basic.route('/example_3', methods=['GET', 'POST'])
def example_3():

    return render_template('example_3.html')


@basic.route('/example_4', methods=['GET', 'POST'])
def example_4():

    return render_template('example_4.html')


@basic.route('/example_5', methods=['GET', 'POST'])
def example_5():
    if request.method == 'POST':
        files = request.files.getlist('input-5[]')
        for file in files:
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

    return render_template('example_5.html')


@basic.route('/example_6', methods=['GET', 'POST'])
def example_6():

    return render_template('example_6.html')


@basic.route('/example_7', methods=['GET', 'POST'])
def example_7():
    if request.method == 'POST':
        files = request.files.getlist('input-7[]')
        for file in files:
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

    return render_template('example_7.html')


@basic.route('/example_8', methods=['GET', 'POST'])
def example_8():
    if request.method == 'POST':
        files = request.files.getlist('input-8[]')
        for file in files:
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

    return render_template('example_8.html')

app/folder/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'


from flask import Blueprint


folder = Blueprint('folder', __name__, template_folder="templates", static_folder='static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本 basic
from . import views

app/folder/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask import render_template, request, jsonify
from . import folder


@folder.route('/example_1', methods=['GET', 'POST'])
def example_1():

    return render_template('ex_1.html')


@folder.route('/example_2', methods=['GET', 'POST'])
def example_2():

    return render_template('ex_2.html')

app/lib/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'


from flask import Blueprint


lib = Blueprint('lib', __name__, static_folder='static')

app/advanced/templates/exam_1.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例1</h1>
<label class="control-label">Planets and Satellites</label>
<input id="input-24" name="input24[]" type="file" multiple class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-24").fileinput({
        initialPreview: [
            'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/631px-FullMoon2010.jpg',
            'http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg'
        ],
        initialPreviewAsData: false,
        initialPreviewConfig: [
            {caption: "Moon.jpg", size: 6930321, width: "120px", key: 1},
            {caption: "Earth.jpg", size: 1218822, width: "120px", key: 2}
        ],
        deleteUrl: "{{ url_for('advanced.delete') }}",
        overwriteInitial: false,
        maxFileSize: 100,
        initialCaption: "进阶示例第一例"
    });
});
</script>
<hr>
<p>
    设置最大的文件上传大小为 100K . 展示服务器上的图片内容,实现 finder 功能. 设置 <code>overwriteInitial</code> 为 <code>false</code>, 新选择的文件不会覆盖原有文件.
</p>
{% endblock %}
{% block title %}
    进阶示例1
{% endblock %}

app/advanced/templates/exam_10.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例10</h1>
<label class="control-label">Select File</label>
<input id="input-43" name="input43[]" type="file" multiple class="file-loading">
<div id="errorBlock" class="help-block"></div>
<script>
$(document).on('ready', function() {
    $("#input-43").fileinput({
        showPreview: false,
        allowedFileExtensions: ["jpg", "jpeg", "gif", "png"],
        elErrorContainer: "#errorBlock"
    });
});
</script>
<br>
<p>
    仅仅允许上传后缀为 "jpg", "gif", "png", "txt" 的文件. 不显示文件预览功能. 且设置错误提示的显示位置.
</p>
{% endblock %}
{% block title %}
    进阶示例10
{% endblock %}

app/advanced/templates/exam_11.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例11</h1>
<label class="control-label">Select File</label>
<input id="input-44" name="input44[]" type="file" multiple class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-44").fileinput({
        uploadUrl: '',
        maxFilePreviewSize: 10240
    });
});
</script>
<br>
<p>
    实现 ajax 上传功能. 设置预览的文件的大小最大为 10M.
</p>
{% endblock %}
{% block title %}
    进阶示例11
{% endblock %}

app/advanced/templates/exam_2.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例2</h1>
<label class="control-label">Planets and Satellites</label>
<input id="input-25" name="input25[]" type="file" multiple class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-25").fileinput({
       initialPreview: [
            'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/631px-FullMoon2010.jpg',
            'http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg'
        ],
        initialPreviewAsData: true,
        initialPreviewConfig: [
            {caption: "Moon.jpg", size: 930321, width: "120px", key: 1, showDelete: false},
            {caption: "Earth.jpg", size: 1218822, width: "120px", key: 2, showZoom: false}
        ],
        deleteUrl: "{{ url_for('advanced.delete') }}",
        overwriteInitial: true,
        initialCaption: "进阶示例第二例"
    });
});
</script>
<hr>
<p>
    设置最大的文件上传大小为 100K . 展示服务器上的图片内容,实现 finder 功能. 设置 <code>overwriteInitial</code> 为 <code>true</code>, 新选择的文件会覆盖原有文件.
</p>
{% endblock %}
{% block title %}
    进阶示例2
{% endblock %}

app/advanced/templates/exam_3.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例3</h1>
<label class="control-label">Select File</label>
<input id="input-20" type="file" class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-20").fileinput({
        browseClass: "btn btn-primary btn-block",
        showCaption: false,
        showRemove: false,
        showUpload: false
    });
});
</script>
{% endblock %}
{% block title %}
    进阶示例3
{% endblock %}

app/advanced/templates/exam_4.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例4</h1>
<label class="control-label">Select File</label>
<input id="input-21" type="file" accept="image/*" class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-21").fileinput({
        previewFileType: "image",
        browseClass: "btn btn-success",
        browseLabel: "Pick Image",
        browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
        removeClass: "btn btn-danger",
        removeLabel: "Delete",
        removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
        uploadClass: "btn btn-info",
        uploadLabel: "Upload",
        uploadIcon: "<i class=\"glyphicon glyphicon-upload\"></i> "
    });
});
</script>
{% endblock %}
{% block title %}
    进阶示例4
{% endblock %}

app/advanced/templates/exam_5.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例5</h1>
<label class="control-label">Select File</label>
<input id="input-22" name="input22[]" type="file" class="file-loading" accept="text/plain" multiple>
<script>
$(document).on('ready', function() {
    $("#input-22").fileinput({
        previewFileType: "text",
        allowedFileExtensions: ["txt", "md", "ini", "text"],
        previewClass: "bg-warning"
    });
});
</script>
{% endblock %}
{% block title %}
    进阶示例5
{% endblock %}

app/advanced/templates/exam_6.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例6</h1>
<label class="control-label">Select File</label>
<input id="input-23" name="input23[]" type="file" multiple class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-23").fileinput({
        showUpload: false,
        layoutTemplates: {
            main1: "{preview}\n" +
            "<div class=\'input-group {class}\'>\n" +
            "   <div class=\'input-group-btn\'>\n" +
            "       {browse}\n" +
            "       {upload}\n" +
            "       {remove}\n" +
            "   </div>\n" +
            "   {caption}\n" +
            "</div>"
        }
    });
});
</script>
{% endblock %}
{% block title %}
    进阶示例6
{% endblock %}

app/advanced/templates/exam_7.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例7</h1>
<label class="control-label">Select File</label>
<input id="input-40" name="input40[]" type="file" class="file" multiple>
<br>
<button type="button" class="btn btn-warning btn-modify">Modify</button>
<script>
$(document).on('ready', function() {
    $(".btn-modify").on("click", function() {
        var $btn = $(this), $input = $("#input-40");
        if ($btn.text() == "Modify") {
            $("#input-40").fileinput("disable").fileinput("refresh", {showUpload: false});
            $btn.html("Revert");
            alert("Hurray! I have disabled the input and hidden the upload button.");
        }
        else {
            $("#input-40").fileinput("enable").fileinput("refresh", {showUpload: true});
            $btn.html("Modify");
            alert("Hurray! I have reverted back the input to enabled with the upload button.");
        }
    });
});
</script>
<br>
<p>
    调用插件方法, 点击 modify 按钮来打开获关闭插件功能.
</p>
{% endblock %}
{% block title %}
    进阶示例7
{% endblock %}

app/advanced/templates/exam_8.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例8</h1>
<label class="control-label">Select File</label>
<input id="input-41" name="input41[]" type="file" multiple class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-41").fileinput({
        maxFileCount: 10,
        allowedFileTypes: ["image", "video"]
    });
});
</script>
<br>
<p>
    仅仅允许上传的文件为图片和视频. 最大上传的文件数是 10.
</p>
{% endblock %}
{% block title %}
    进阶示例8
{% endblock %}

app/advanced/templates/exam_9.html
{% extends 'advanced_common/base.html' %}
{% block content %}
<h1>进阶示例9</h1>
<label class="control-label">Select File</label>
<input id="input-42" name="input42[]" type="file" multiple class="file-loading">
<script>
$(document).on('ready', function() {
    $("#input-42").fileinput({
        maxFileCount: 10,
        allowedFileExtensions: ["jpg", "gif", "png", "txt"]
    });
});
</script>
<br>
<p>
    仅仅允许上传后缀为 "jpg", "gif", "png", "txt" 的文件. 最大上传的文件数是 10.
</p>
{% endblock %}
{% block title %}
    进阶示例9
{% endblock %}

app/basic/templates/example_1.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例1 -- 自动展示缩略图</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-1" name="input-1" type="file" class="file">
</form>

{% endblock %}
{% block title %}
    基本示例1 -- 自动展示缩略图
{% endblock %}

app/basic/templates/example_2.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例2 -- 隐藏展示缩略图</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-2" name="input-2" type="file" class="file"  data-show-preview="false">
</form>
{% endblock %}
{% block title %}
    基本示例2 -- 隐藏展示缩略图
{% endblock %}

app/basic/templates/example_3.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例3 -- 利用 file input 属性控制相关选项,如本例可实现多文件上传,但不显示上传按钮</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-3" name="input3[]" type="file" class="file" multiple data-show-upload="false" data-show-caption="true">
</form>
{% endblock %}
{% block title %}
    基本示例3 -- 利用 file input 属性控制相关选项,如本例可实现多文件上传,但不显示上传按钮
{% endblock %}

app/basic/templates/example_4.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例4 -- 设置属性为只读或不可用</h1>
<label class="control-label">Select File</label>
<label class="control-label">Readonly Input</label>
<input id="input-4a" type="file" class="file" readonly="true">
<label class="control-label">Disabled Input</label>
<input id="input-4b" type="file" class="file" disabled="true">
{% endblock %}
{% block title %}
    基本示例4 -- 设置属性为只读或不可用
{% endblock %}

app/basic/templates/example_5.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例5 -- 设置为单按钮并隐藏文件选择输入框,在上传时显示上传等待图标</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-5" name="input-5[]" type="file" multiple class="file-loading">
</form>
<script>
$(document).on('ready', function() {
    $("#input-5").fileinput({showCaption: false});
});
</script>
{% endblock %}
{% block title %}
    基本示例5 -- 设置为单按钮并隐藏文件选择输入框,在上传时显示上传等待图标
{% endblock %}

app/basic/templates/example_6.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例6 -- 设置最大上传的文件数为10</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-6" name="input6[]" type="file" multiple class="file-loading">
</form>
<script>
$(document).on('ready', function() {
    $("#input-6").fileinput({
        showUpload: false,
        maxFileCount: 10,
        mainClass: "input-group-lg"
    });
});
</script>
{% endblock %}
{% block title %}
    基本示例6 -- 设置最大上传的文件数为10
{% endblock %}

app/basic/templates/example_7.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例7 -- 设置允许上传的文件格式</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-7" name="input-7[]" multiple type="file" class="file file-loading" data-allowed-file-extensions='["csv", "txt"]'>
</form>
{% endblock %}
{% block title %}
    基本示例7 -- 设置允许上传的文件格式
{% endblock %}

app/basic/templates/example_8.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例8 -- 使用rtl样式,让文件选择按钮居左</h1>
<span>注意:引入样式文件的时候, css/fileinput-rtl.css 必须在 the css/fileinput.css 之后引入</span>
<div dir=rtl>
    <label class="control-label">Select File</label>
</div>
<!-- note that your input must just set the `rtl` data property of the plugin or in your javascript code -->
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-8" name="input-8[]" multiple type="file" class="file-loading">
</form>
<script>
$(document).on('ready', function() {
    $("#input-8").fileinput({
        rtl: true,
        allowedFileExtensions: ["jpg", "png", "gif"]
    });
});
</script>
{% endblock %}
{% block title %}
    基本示例8 -- 使用rtl样式,让文件选择按钮居左
{% endblock %}
{% block css %}
    {{ super() }}
    <link href="{{ url_for('lib.static',filename='css/fileinput-rtl.min.css') }}" media="all" rel="stylesheet" type="text/css" />
{% endblock %}

app/folder/templates/ex_1.html
{% extends 'folder_common/base.html' %}
{% block content %}
<h1>文件夹上传示例1</h1>
<label class="control-label">Upload File From Folder</label>
<input id="input-folder-1" type="file" class="file-loading" webkitdirectory>
<script>
$(document).on('ready', function() {
    $("#input-folder-1").fileinput({
        browseLabel: '选择文件夹...'
    });
});
</script>
<hr>
<p>
    设置选择文件夹功能, 但只支持选择文件夹内的单一文件.
</p>
{% endblock %}
{% block title %}
    文件夹上传示例1
{% endblock %}

app/folder/templates/ex_2.html
{% extends 'folder_common/base.html' %}
{% block content %}
<h1>文件夹上传示例2</h1>
<label class="control-label">Upload All Files From Folder</label>
<input id="input-folder-2" name="input-folder-2[]" class="file-loading" type="file" multiple webkitdirectory accept="image/*">
<div id="errorBlock" class="help-block"></div>
<script>
$(document).on('ready', function() {
    $("#input-folder-2").fileinput({
        browseLabel: 'Select Folder...',
        previewFileIcon: '<i class="fa fa-file"></i>',
        allowedPreviewTypes: null, // set to empty, null or false to disable preview for all types
        previewFileIconSettings: {
            'doc': '<i class="fa fa-file-word-o text-primary"></i>',
            'xls': '<i class="fa fa-file-excel-o text-success"></i>',
            'ppt': '<i class="fa fa-file-powerpoint-o text-danger"></i>',
            'jpg': '<i class="fa fa-file-photo-o text-warning"></i>',
            'pdf': '<i class="fa fa-file-pdf-o text-danger"></i>',
            'zip': '<i class="fa fa-file-archive-o text-muted"></i>',
            'htm': '<i class="fa fa-file-code-o text-info"></i>',
            'txt': '<i class="fa fa-file-text-o text-info"></i>',
            'mov': '<i class="fa fa-file-movie-o text-warning"></i>',
            'mp3': '<i class="fa fa-file-audio-o text-warning"></i>',
        },
        previewFileExtSettings: {
            'doc': function(ext) {
                return ext.match(/(doc|docx)$/i);
            },
            'xls': function(ext) {
                return ext.match(/(xls|xlsx)$/i);
            },
            'ppt': function(ext) {
                return ext.match(/(ppt|pptx)$/i);
            },
            'jpg': function(ext) {
                return ext.match(/(jp?g|png|gif|bmp)$/i);
            },
            'zip': function(ext) {
                return ext.match(/(zip|rar|tar|gzip|gz|7z)$/i);
            },
            'htm': function(ext) {
                return ext.match(/(php|js|css|htm|html)$/i);
            },
            'txt': function(ext) {
                return ext.match(/(txt|ini|md)$/i);
            },
            'mov': function(ext) {
                return ext.match(/(avi|mpg|mkv|mov|mp4|3gp|webm|wmv)$/i);
            },
            'mp3': function(ext) {
                return ext.match(/(mp3|wav)$/i);
            },
        }
    });
});
</script>
<hr>
<p>
    设置选择文件夹功能, 支持选择文件夹内的所有文件.
</p>
{% endblock %}
{% block title %}
    文件夹上传示例2
{% endblock %}

app/folder/templates/folder_common/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{{ url_for('lib.static', filename='favicon.ico')}}">

        <title>{% block title %}{% endblock %}</title>
        {% block css %}
            <!-- 新 Bootstrap 核心 CSS 文件 -->
            <link rel="stylesheet" href="{{ url_for('lib.static', filename='css/bootstrap.min.css') }}">

            <!-- 可选的Bootstrap主题文件（一般不用引入） -->
            <link rel="stylesheet" href="{{ url_for('lib.static', filename='css/bootstrap-theme.min.css') }}">

            <!-- 个性化主题文件 -->
            <!-- font-awesome样式主题文体 -->
            <link href="{{ url_for('lib.static',filename='css/font-awesome.css') }}" media="all" rel="stylesheet" type="text/css" />
            <!-- fileinput样式主题文体 -->
            <link href="{{ url_for('lib.static',filename='css/fileinput.min.css') }}" media="all" rel="stylesheet" type="text/css" />
        {% endblock %}

        {% block js %}
            <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
            <script src="{{ url_for('lib.static', filename='js/jquery.min.js') }}"></script>

            <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
            <script src="{{ url_for('lib.static', filename='js/bootstrap.min.js') }}"></script>

            <!-- 个性化 js 文件 -->
            <!-- piexif.min.js is only needed if you wish to resize images before upload to restore exif data.
             This must be loaded before fileinput.min.js -->
            <script src="{{ url_for('lib.static',filename='js/plugins/piexif.min.js') }}" type="text/javascript"></script>
            <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
                 This must be loaded before fileinput.min.js -->
            <script src="{{ url_for('lib.static',filename='js/plugins/sortable.min.js') }}" type="text/javascript"></script>
            <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
                 This must be loaded before fileinput.min.js -->
            <script src="{{ url_for('lib.static',filename='js/plugins/purify.js') }}" type="text/javascript"></script>
            <!-- the main fileinput plugin file -->
            <script src="{{ url_for('lib.static',filename='js/fileinput.min.js') }}"></script>
            <!-- optionally if you need a theme like font awesome theme you can include
                it as mentioned below -->
            <script src="{{ url_for('lib.static',filename='js/themes/fa/theme.min.js') }}"></script>
            <!-- optionally if you need translation for your language then include
                locale file as mentioned below -->
            <script src="{{ url_for('lib.static',filename='js/locales/zh.js') }}"></script>

        {% endblock %}
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-offset-2">
                    <div class="col-xs-12 col-sm-8">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div><!--/row-->
        </div><!--/.container-->
    </body>
</html>